allow-lan: true
mode: rule
ipv6: false
# 默认情况下, Clash 将日志打印到 STDOUT
# 日志级别: info / warning / error / debug / silent
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: /etc/clash/dashboard

dns:
        enable: true
        listen: 0.0.0.0:53
        enhanced-mode: fake-ip
        fake-ip-range: 198.18.0.1/16
        fake-ip-filter:
                - '*.lan'
        nameserver:
                - 114.114.114.114
                - 8.8.8.8
                - tcp://8.8.8.8:53
                - https://1.1.1.1/dns-query
        nameserver-policy:
                '+.lan': 192.168.1.1 # 指定硬路由IP地址，需要在路由器端做dns劫持，比如指定raspberrypi.lan为192.168.1.2
tun:
        enable: true
        stack: system
        dns-hijack:
                - any:53
        auto-route: true
        # auto-redir: true
        auto-detect-interface: true

proxies:
        - name: "us-ss"
          type: ss
          server: 1.2.3.4
          port: 1234
          cipher: aes-256-gcm
          password: "password0"
          plugin: obfs
          plugin-opts:
                  mode: tls
                  host: bing.com
                  
proxy-groups:
        - name: proxy
          type: select
          proxies:
                  - us-ss
                  - DIRECT
rules:
        - DOMAIN-SUFFIX, google.com, proxy
        - DOMAIN-KEYWORD, google, proxy
        - DOMAIN-SUFFIX, youtube.com, proxy
        - DOMAIN-SUFFIX, android.com, proxy
        - DOMAIN-SUFFIX, github.com, proxy
        - DOMAIN-SUFFIX, teddysun.com, proxy
        - DOMAIN-SUFFIX, maxmind.com, proxy
        - DOMAIN-SUFFIX, edu.cn, DIRECT
        - IP-CIDR, 127.0.0.0/8, DIRECT
        - IP-CIDR, 192.168.0.0/16, DIRECT
        - SRC-PORT, 8999, DIRECT
        - PROCESS-NAME, qbittorrent-nox, DIRECT
        - GEOIP, LAN, DIRECT
        - GEOIP, CN, DIRECT
        - MATCH, proxy
